local shell = require("shell")
local filesystem = require("filesystem")
local computer = require("computer")

shell.setWorkingDirectory("/home/myaenetwork/")
shell.execute("rm web.lua")
shell.execute("rm account.lua")

print("Updating")
shell.execute("wget https://raw.githubusercontent.com/MineappleFX/MineappleFX.github.io/main/account.lua")
shell.execute("wget https://raw.githubusercontent.com/MineappleFX/MineappleFX.github.io/main/web.lua")
shell.execute("wget https://raw.githubusercontent.com/MineappleFX/MineappleFX.github.io/main/accountAux.lua")
shell.execute("wget https://raw.githubusercontent.com/MineappleFX/MineappleFX.github.io/main/webAux.lua")
shell.execute("wget https://raw.githubusercontent.com/MineappleFX/MineappleFX.github.io/main/MaenUpdater.lua")
shell.setWorkingDirectory("/home/")
print("Rebooting")
computer.shutdown(true)
